export default function English() {
  const wa = 'https://wa.me/5511913195079?text=' + encodeURIComponent("Hi! I'd like to discuss a website project in English.")
  return <main lang="en"><section id="hero"><div className="container hero-grid"><div><div className="tag">S&M Digital / Brazil</div><h1>Your business.<br /><span className="text-cyan">Thoughtfully<br />built online.</span></h1><p className="hero-sub">We design and develop business websites and landing pages. Clear content, considered design and a layout that works on mobile.</p><a className="btn btn-primary" href="#english-contact">Discuss your project</a></div><figure className="studio-figure"><img src="/images/development.png" alt="Development workspace with a code editor and website preview" /><figcaption>Strategy, design and development.</figcaption></figure></div></section>
  <section><div className="container"><div className="section-header"><div className="tag">Our services</div><h2>What can we build for you?</h2></div><div className="grid-3">{[
    ['Business websites', 'A multi-page home for your company, services and contact information.', 'Estimated BRL 1,900–6,000 / timing confirmed in the proposal'],
    ['Landing pages', 'One focused page for a product, service or advertising campaign.', 'Estimated BRL 900–1,600 / timing confirmed in the proposal'],
    ['Maintenance & support', 'Backups, updates and content changes according to your monthly plan.', 'Estimated BRL 199–699 per month'],
  ].map(([t,d,price]) => <article className="service-card english-card" key={t}><h3>{t}</h3><p>{d}</p><div className="service-price">{price}</div></article>)}</div><p className="scope-note">Indicative estimates in Brazilian reais, not fixed quotes. Final scope and timing are agreed in your proposal. Domain, hosting and third-party services are billed separately.</p></div></section>
  <section className="content-section"><div className="container grid-2"><h2>A clear process,<br />from idea to launch.</h2><div><h3>Discovery and scope</h3><p>Tell us about your business, audience and priorities. We agree on the pages and features you need.</p><h3 className="mt-2">Design and development</h3><p>Review the structure and visual direction before we build your website.</p><h3 className="mt-2">Review and launch</h3><p>We review the result together and help you prepare for publication.</p></div></div></section>
  <section id="english-contact"><div className="container"><div className="cta-box"><div className="tag">Let's talk</div><h2>Tell us about<br />your project.</h2><p>Send your requirements in English by email or WhatsApp. Include your business, budget and preferred timeline.</p><div className="btn-group"><a className="btn btn-cyan" href={wa} target="_blank" rel="noreferrer">Contact via WhatsApp</a><a className="btn btn-outline" href="mailto:smdigitalcontato1@gmail.com?subject=Website%20project%20enquiry">Email us in English</a></div></div></div></section></main>
}
